version: '3.5'
services: 
    rabbitmq:
        image: rabbitmq:management
        container_name: RMQ
        ports: 
            - "5672:5672"
            - "15672:15672"
        environment: 
            - "RABBITMQ_DEFAULT_PASS=guest"
            - "RABBITMQ_DEFAULT_USER=guest"
